"""Add new table

Revision ID: 73d23772d14b
Revises: 
Create Date: 2024-11-12 17:16:32.249081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d23772d14b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('woodcutting', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_attack'), 'user_data', ['attack'], unique=False)
    op.create_index(op.f('ix_user_data_display_name'), 'user_data', ['display_name'], unique=False)
    op.create_index(op.f('ix_user_data_id'), 'user_data', ['id'], unique=False)
    op.create_index(op.f('ix_user_data_overall'), 'user_data', ['overall'], unique=False)
    op.create_index(op.f('ix_user_data_woodcutting'), 'user_data', ['woodcutting'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_data_woodcutting'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_overall'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_id'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_display_name'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_attack'), table_name='user_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
